# Copyright (c) 2019-2021, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

image: Ubuntu1804

skip_non_tags: true

install:
  sh: |-
      sudo apt-get update -qq
      sudo -E apt-get install -y acpica-tools gcc-aarch64-linux-gnu python3-distutils uuid-dev
      git submodule update --init --recursive
      patch --binary -d edk2 -p1 -i ../0001-MdeModulePkg-UefiBootManagerLib-Signal-ReadyToBoot-o.patch
      patch --binary -d edk2 -p1 -i ../iscsi_reenable.patch

before_build:
  ps: |-
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/08ed7a0c9ad4d9db559aaec462520ab435c7ce1c/boot/fixup4.dat
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/08ed7a0c9ad4d9db559aaec462520ab435c7ce1c/boot/start4.elf
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-4-b.dtb
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-cm4.dtb
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-400.dtb
      Start-FileDownload https://github.com/raspberrypi/firmware/raw/master/boot/overlays/miniuart-bt.dtbo
      mkdir overlays
      move miniuart-bt.dtbo overlays

build_script:
  sh: ./build_firmware.sh

after_build:
  sh: |-
      7z a RPi4_UEFI_Firmware_$APPVEYOR_REPO_TAG_NAME.zip $APPVEYOR_BUILD_FOLDER/Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd $APPVEYOR_BUILD_FOLDER/*.dtb $APPVEYOR_BUILD_FOLDER/config.txt $APPVEYOR_BUILD_FOLDER/fixup4.dat $APPVEYOR_BUILD_FOLDER/start4.elf overlays/miniuart-bt.dtbo $APPVEYOR_BUILD_FOLDER/Readme.md
      sha256sum $APPVEYOR_BUILD_FOLDER/Build/RPi4/DEBUG_GCC5/FV/RPI_EFI.fd $APPVEYOR_BUILD_FOLDER/Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd RPi4_UEFI_Firmware_$APPVEYOR_REPO_TAG_NAME.zip

artifacts:
  - path: 'Build/RPi4/DEBUG_GCC5/FV/RPI_EFI.fd'
    name: DEBUG RPi4 UEFI Firmware
  - path: 'Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd'
    name: RELEASE RPi4 UEFI Firmware
  - path: '*.zip'
    name: RPi 4 UEFI Firmware

deploy:
  - provider: GitHub
    on:
      APPVEYOR_REPO_TAG: true
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: Raspberry Pi 4 UEFI Firmware $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: NZrkzJXfvf2ZTfcyOtQ8l/sOFvNlQ1SovMA1PgS8QhUDrKgRbCEAuzSdCY5Ytucp
    artifact: /.*\.zip/
    draft: false
    prerelease: false
